version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14 # Choose the Node.js version you need
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Start Application
          command: node app.js


