version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14 # Choose the Node.js version you need
    working_directory: ~/app
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: echo "Deploying to production server" # You can replace this with actual deployment commands

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
