version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:3.11
    steps:
      - checkout
      - run: node index.js
  test:
    docker:
      - image: cimg/node:3.11
    steps:
      - checkout
      - run: node index.js
  deploy:
    docker:
      - image: cimg/node:3.11
    steps:
      - run: echo "Deploying to production server"

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build 
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
