version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14 # Choose the Node.js version you need
    working_directory: ~/app
    steps:
      - checkout
      - run: npm install
      - run: node app.js # Replace 'app.js' with the name of your Node.js entry file

  test:
    docker:
      - image: circleci/node:14
    working_directory: ~/app
    steps:
      - checkout
      - run: npm install
      - run: npm test

  deploy:
    docker:
      - image: circleci/node:14
    working_directory: ~/app
    steps:
      - run: echo "Deploying to production server" # You can replace this with actual deployment commands

workflows:
  version: 2
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main # Change 'main' to the branch you want to deploy from
